### PR TITLE
#13 - Corrected the method call on ClassLoader so that it's compatible w...

### PR DESCRIPTION
**Pull request by fotomerchant**
Fixes [#13]. Will break compatibility with Symfony 2.3 and below.

### CODE REVIEW

**Comment by paulandrieux** [comment]
This PR seems OK, could you merge it ?

**Comment by gmoreira** [comment]
@phiamo Can we get this merged?

**Comment by lutangar** [comment]
+1

**Comment by Nickolaus** [comment]
+1, but it has no fallback for symfony < 2.4

**Pull request merged**
